### PR TITLE
Jp computers create delete

### LINKED ISSUE #14: IT should be able to assign employee when creating computer
**Given** a user wants to assign a new computer to an employee
**When** the user clicks on the create computer affordance
**Then** the creation form should include an affordance that lists all employees

**Given** the user is viewing the computer creation for
**When** the user fills out all properties for the computer
**And** has chosen an employee
**Then** the user should be redirected back to the list of computers

**Given** the user has created a new computer
**When** the user is redirected to the computer list
**Then** the currently assigned employee's full name should be displayed in the list

### PR DESCRIPTION
**Pull request by Preston-Jake**
Assign Employee when creating a computer and display full employee name from list view
Fixes #14

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Checklist computer list for employee fullname and select an employee when creating a computer

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by JoelVenable — CHANGES_REQUESTED** [review]
Looks like the list view is missing the employee name.  We worked on that together so I'm guessing it just needs to be committed.

**Comment by Preston-Jake** [comment]
I committed and re-pushed -- everything should be up to date

**Review by JoelVenable — APPROVED** [review]
Thanks.  Looks good.

**Review by Sglavin85 — APPROVED** [review]
good to go

**Pull request merged**
